# Generated by Django 6.1.1 on 2026-09-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('service_type', models.CharField(choices=[('police', 'Police'), ('ambulance', 'Ambulance / Medical EMS'), ('fire', 'Fire & Rescue'), ('disaster', 'Disaster Management Authority'), ('poison', 'Poison Control Center'), ('helpline', 'Emergency Response Support System')], db_index=True, max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('GLOBAL', 'International / Universal'), ('US', 'United States / Canada'), ('IN', 'India'), ('UK', 'United Kingdom'), ('EU', 'European Union'), ('AU', 'Australia')], db_index=True, default='GLOBAL', max_length=50)),
                ('is_primary', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalICEContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(default='Family', max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('notify_on_sos', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
