# Generated by Django 6.1.1 on 2026-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contacts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
