# Generated by Django 6.1.1 on 2026-09-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('accident', 'Road & Traffic Accident'), ('fire', 'Fire & Smoke Inhalation'), ('medical', 'Medical Emergency & First Aid'), ('flood', 'Flood & Water Hazard'), ('earthquake', 'Earthquake & Collapse'), ('missing_person', 'Missing Person / Abduction'), ('chemical', 'Hazardous Materials & Gas Leak'), ('general', 'General Emergency')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('severity_default', models.CharField(default='HIGH', max_length=20)),
                ('source_agency', models.CharField(default='WHO / Red Cross / FEMA', max_length=150)),
                ('summary', models.TextField()),
                ('steps', models.JSONField(default=list, help_text='Numbered safety steps')),
                ('dos', models.JSONField(blank=True, default=list, help_text='Recommended immediate actions')),
                ('donts', models.JSONField(blank=True, default=list, help_text='Actions to avoid at all costs')),
                ('keywords', models.TextField(help_text='Keywords used for RAG semantic matching')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
