# Generated by Django 6.1.1 on 2026-09-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(db_index=True, max_length=150)),
                ('priority', models.IntegerField(db_index=True, default=1)),
                ('instruction', models.TextField()),
                ('recommended_service', models.CharField(blank=True, max_length=150)),
                ('verification', models.CharField(blank=True, max_length=255)),
                ('trusted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Emergency Knowledge',
                'verbose_name_plural': 'Emergency Knowledge',
                'indexes': [models.Index(fields=['emergency_type'], name='knowledge_b_emergen_1e8fee_idx'), models.Index(fields=['priority'], name='knowledge_b_priorit_1193f7_idx')],
                'unique_together': {('emergency_type', 'instruction')},
            },
        ),
    ]
