# Generated by Django 6.1.1 on 2026-09-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital & Trauma Center'), ('police', 'Police Station'), ('fire', 'Fire & Rescue Station'), ('shelter', 'Evacuation Shelter & Relief Center')], db_index=True, max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=50)),
                ('is_24_hours', models.BooleanField(default=True)),
                ('emergency_services', models.CharField(default='Emergency Room, Trauma Care', max_length=255)),
                ('bed_status', models.CharField(default='Available', max_length=50)),
                ('rating', models.FloatField(default=4.8)),
            ],
        ),
    ]
