# Generated by Django 6.1.1 on 2026-09-18 11:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('emergency_type', models.CharField(default='General Emergency', max_length=150)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical - Imminent Danger'), ('HIGH', 'High - Immediate Assistance Required'), ('MEDIUM', 'Medium - Urgent Care'), ('LOW', 'Low - Informational / Minor')], db_index=True, default='HIGH', max_length=20)),
                ('ai_response', models.JSONField(blank=True, default=dict)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Response'), ('IN_PROGRESS', 'In Progress / Dispatched'), ('RESOLVED', 'Resolved / Safe'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
